### ISSUE TITLE
Could you tell me how to install it?

### ISSUE THREAD

**Issue by archonwang** [Sacret/redmine-charts#3]
Could you tell me how to install it? 
Thanks

**Comment by Perlence** [comment]
We've added installation guide, check it out https://github.com/Sacret/redmine-charts#installation

**Comment by archonwang** [comment]
@Perlence ,

I installed nodejs 4.4.5.
I installed as the instruction ,but at last when I open the site, I got an error

> Something went wrong! Can't load projects info. Please try again later
> Something went wrong! Can't load default project info. Please try again later

I not sure whether I have missed something, where can I fill the redmine API Key? Thanks

**Comment by archonwang** [comment]
there's log information

```
[root@localhost routes]# npm start

> redmine-charts@1.2.1 start /opt/redmine-charts
> node server.js

GET / 304 18.252 ms - -
GET /css/style.css 404 9.029 ms - 23
GET /bower_components/ladda/dist/ladda-themeless.min.css 404 9.501 ms - 23
GET /bower_components/bootstrap-daterangepicker/daterangepicker-bs3.css 404 2.247 ms - 23
GET /js/components.js 404 2.483 ms - 23
GET /js/app.js 304 3.086 ms - -
GET /js/projects.js 304 2.297 ms - -
GET /css/style.css 404 0.926 ms - 23
GET /js/components.js 404 0.774 ms - 23
GET /bower_components/ladda/dist/ladda-themeless.min.css 404 0.694 ms - 23
GET /js/app.js 304 0.682 ms - -
GET /bower_components/bootstrap-daterangepicker/daterangepicker-bs3.css 404 0.783 ms - 23
GET /js/projects.js 304 0.838 ms - -
```

**Comment by Perlence** [comment]
You can get your API key from your account page. Go to http://{redmine-host}/my/account and look for **API access key**.

**Comment by archonwang** [comment]
it seems that I have made mistake when I bower install for I used root account.
there's correct command line in CentOS when using root.

`bower install --allow-root`

**Comment by archonwang** [comment]
another question, how can I filled in my redmine uri,  I have modified the routes/index.coffee but it seems have no effect.

**Comment by archonwang** [comment]
```
npm-debug error

[root@localhost redmine-charts]# vim npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@2.15.5
3 info using node@v4.4.5
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart redmine-charts@1.2.1
6 info start redmine-charts@1.2.1
7 verbose unsafe-perm in lifecycle true
8 info redmine-charts@1.2.1 Failed to exec start script
9 verbose stack Error: redmine-charts@1.2.1 start: `node server.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid redmine-charts@1.2.1
11 verbose cwd /opt/redmine-charts
12 error Linux 2.6.32-573.22.1.el6.x86_64
13 error argv "/usr/bin/node" "/usr/bin/npm" "start"
14 error node v4.4.5
15 error npm  v2.15.5
16 error code ELIFECYCLE
17 error redmine-charts@1.2.1 start: `node server.js`
17 error Exit status 1
18 error Failed at the redmine-charts@1.2.1 start script 'node server.js'.
18 error This is most likely a problem with the redmine-charts package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node server.js
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs redmine-charts
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls redmine-charts
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by Sacret** [comment]
Hello, dear @archonwang. Could you please run the server and open in your browser such a link:
http://localhost:3000/api/users/current.json?key=[YOUR_API_KEY]

Let me know if you get correct JSON-data
Thanks!
